/**
 * ESLint configuration for api-server
 *
 * Strict TypeScript checking for the Cloudflare Worker.
 */
import js from '@eslint/js'
import prettierConfig from 'eslint-config-prettier'
import tseslint from 'typescript-eslint'
import globals from 'globals'
import noConfusableCallbackParams from '../../eslint-plugins/no-confusable-callback-params.js'

/**
 * Node-only globals and built-in modules, banned across `src/**`.
 *
 * `wrangler.toml` carries no `nodejs_compat` flag, so in the deployed Worker none of these exist:
 * a reference to one throws at the moment the line runs, for every user, forever. A
 * `Buffer.from()` in the license key encoder did exactly that and made every purchase fail. It
 * survived review because the Vitest `node` project has all of this (and
 * `@cloudflare/vitest-pool-workers` force-enables `nodejs_compat_v2` for its own runner, so the
 * `workerd` project has it too), which is why the ban covers TESTS as well as production code:
 * a test written against a Node global proves nothing about the runtime we deploy to.
 *
 * ❌ Don't widen this by turning on `nodejs_compat`. A test file that legitimately drives the
 * Worker FROM Node (the `createTestHarness` suites, the `node:sqlite` fixtures) opts out per line
 * with `// eslint-disable-next-line no-restricted-imports -- <reason>`, so the exception is visible
 * and argued rather than global.
 */
const workerRuntimeNote =
  'The Worker deploys without `nodejs_compat`, so this does not exist in production and referencing it throws for every user.'

/** Node globals, each with the web-standard replacement that works in workerd. */
const bannedNodeGlobals = [
  { name: 'Buffer', use: '`atob` / `btoa`, `TextEncoder` / `TextDecoder`, or `Uint8Array`' },
  { name: 'process', use: 'the `Bindings` env object the Worker is handed' },
  { name: 'global', use: '`globalThis`' },
  { name: '__dirname', use: '`new URL(..., import.meta.url)`' },
  { name: '__filename', use: '`import.meta.url`' },
  { name: 'require', use: 'a static `import`' },
  { name: 'module', use: 'ESM `export`' },
  { name: 'exports', use: 'ESM `export`' },
  { name: 'setImmediate', use: '`setTimeout(fn, 0)`, or `ctx.waitUntil` for work that outlives the response' },
  { name: 'clearImmediate', use: '`clearTimeout`' },
].map(({ name, use }) => ({ name, message: `${workerRuntimeNote} Use ${use} instead.` }))

/**
 * Bare Node built-in specifiers. `node:*` is caught by pattern; these are the same modules spelled
 * without the prefix, which resolve in Node and fail to bundle for the Worker.
 */
const bannedBareNodeModules = [
  'assert',
  'buffer',
  'child_process',
  'crypto',
  'events',
  'fs',
  'fs/promises',
  'http',
  'https',
  'net',
  'os',
  'path',
  'stream',
  'timers',
  'tls',
  'url',
  'util',
  'worker_threads',
  'zlib',
]

export default tseslint.config(
  {
    // `worker-configuration.d.ts` is generated by `wrangler types`: upstream runtime typings, not
    // ours to lint (it even ships eslint-disable directives that don't match our rule set).
    ignores: ['dist', 'node_modules', '.wrangler', 'keys', 'worker-configuration.d.ts'],
  },
  js.configs.recommended,
  prettierConfig,
  ...tseslint.configs.strictTypeChecked.map((config) => ({
    ...config,
    files: ['**/*.ts'],
  })),
  {
    files: ['**/*.ts'],
    plugins: {
      '@typescript-eslint': tseslint.plugin,
    },
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.node,
        ...globals.es2021,
      },
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // `ignoreRestSiblings`: tests destructure a field out of a fixture just to omit it from
      // `...rest`, and never read the extracted binding itself.
      '@typescript-eslint/no-unused-vars': ['error', { ignoreRestSiblings: true }],
      '@typescript-eslint/no-unsafe-assignment': 'error',
      '@typescript-eslint/no-unsafe-call': 'error',
      '@typescript-eslint/no-unsafe-member-access': 'error',
      '@typescript-eslint/no-unsafe-return': 'error',
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/await-thenable': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      '@typescript-eslint/require-await': 'error',
      '@typescript-eslint/no-explicit-any': 'error',
      'no-console': 'off', // Allow console in server code
      complexity: ['error', { max: 15 }],
    },
  },
  {
    files: ['scripts/*.js', 'test/*.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.node,
      },
    },
  },
  {
    // Test fixtures delete dynamic keys off mock objects, which runtime code shouldn't.
    files: ['src/**/*.test.ts'],
    rules: {
      '@typescript-eslint/no-dynamic-delete': 'off',
    },
  },
  {
    // Shared with the desktop app and analytics dashboard, which register the same rule
    // under the same name.
    files: ['src/**/*.ts'],
    plugins: { cmdr: { rules: { 'no-confusable-callback-params': noConfusableCallbackParams } } },
    rules: { 'cmdr/no-confusable-callback-params': 'error' },
  },
  {
    // The Node ban. Everything under `src/` either ships to the Worker or claims to test what does,
    // so the whole tree is in scope; see `bannedNodeGlobals` above for why tests are included and
    // how a Node-side test driver opts out. `scripts/` and `test/` are Node programs that never
    // reach the Worker, so they stay out of it.
    files: ['src/**/*.ts'],
    rules: {
      'no-restricted-globals': ['error', ...bannedNodeGlobals],
      'no-restricted-imports': [
        'error',
        {
          paths: bannedBareNodeModules.map((name) => ({
            name,
            message: `${workerRuntimeNote} Reach for the Worker runtime's own API, or a dependency that targets workers.`,
          })),
          patterns: [
            {
              group: ['node:*'],
              message: `${workerRuntimeNote} Reach for the Worker runtime's own API, or a dependency that targets workers.`,
            },
          ],
        },
      ],
    },
  },
)
